/**
 * Curated template × model license overview for demo / commercial clearance.
 * Source of truth for Settings → Template licenses popup.
 * Keep in sync with registry seed licenses when models change.
 */

export type TemplateLicenseTone = "safe" | "nc" | "caution";

export type TemplateLicenseRow = {
  id: string;
  title: string;
  models: string;
  licenses: string;
  impact: string;
  cluster: string;
  /** Short commercial label: Safe | Not safe */
  commercial: "Safe" | "Not safe";
  conference: string;
  final: string;
  tone: TemplateLicenseTone;
};

/** All bundled templates — commercial-safe first, then NC, then TBD. */
export const TEMPLATE_LICENSE_MATRIX: TemplateLicenseRow[] = [
  {
    id: "hello-groovy",
    title: "Hello GroovyUI",
    models: "kokoro-82m",
    licenses: "kokoro-82m: Apache-2.0",
    impact: "High",
    cluster: "Onboarding",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "podcast-denoise",
    title: "Podcast Denoise",
    models: "deepfilternet-v3",
    licenses: "deepfilternet-v3: MIT",
    impact: "High",
    cluster: "Speech cleanup",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "stem-separation",
    title: "Stem Separation",
    models: "demucs-v4",
    licenses: "demucs-v4: MIT",
    impact: "High",
    cluster: "Stems",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "ace-step-1.5",
    title: "Text to Music- ACE Step 1.5",
    models: "ace-step-1.5",
    licenses: "ace-step-1.5: MIT",
    impact: "High",
    cluster: "Text→music",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "transcribe-and-diarize",
    title: "Transcribe and Diarize",
    models: "whisper-large-v3-turbo, pyannote-diarization-3.1",
    licenses: "whisper-large-v3-turbo: MIT; pyannote-diarization-3.1: MIT",
    impact: "High",
    cluster: "ASR + speakers",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe (cite pyannote; HF gated)",
    tone: "safe",
  },
  {
    id: "transcribe-dialogue",
    title: "Transcribe Dialogue",
    models: "whisper-large-v3-turbo",
    licenses: "whisper-large-v3-turbo: MIT",
    impact: "High",
    cluster: "ASR",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "ab-compare-demo",
    title: "A/B Compare Demo",
    models: "deepfilternet-v3",
    licenses: "deepfilternet-v3: MIT",
    impact: "Med",
    cluster: "Studio UX",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "sample-verify",
    title: "Sample Verify",
    models: "—",
    licenses: "— (DSP / core only)",
    impact: "Med",
    cluster: "Sample integrity",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "cleanup-and-transcribe",
    title: "Cleanup and Transcribe",
    models: "deepfilternet-v3, whisper-large-v3-turbo",
    licenses: "deepfilternet-v3: MIT; whisper-large-v3-turbo: MIT",
    impact: "Med",
    cluster: "Speech cleanup",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "compare-whisper-sizes",
    title: "Compare Whisper Sizes",
    models: "deepfilternet-v3, whisper-large-v3-turbo, whisper-small-en",
    licenses:
      "deepfilternet-v3: MIT; whisper-large-v3-turbo: MIT; whisper-small-en: MIT",
    impact: "High",
    cluster: "ASR compare",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "script-to-vo-master",
    title: "Script to VO Master",
    models: "kokoro-82m, deepfilternet-v3",
    licenses: "kokoro-82m: Apache-2.0; deepfilternet-v3: MIT",
    impact: "High",
    cluster: "VO finish",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "karaoke-guide-vocal",
    title: "Karaoke Guide Vocal",
    models: "demucs-v4, kokoro-82m",
    licenses: "demucs-v4: MIT; kokoro-82m: Apache-2.0",
    impact: "High",
    cluster: "Karaoke",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe (owned/bundled mix only)",
    tone: "safe",
  },
  {
    id: "instrumental-tts-dub",
    title: "Instrumental TTS Dub",
    models: "demucs-v4, whisper-large-v3-turbo, kokoro-82m",
    licenses:
      "demucs-v4: MIT; whisper-large-v3-turbo: MIT; kokoro-82m: Apache-2.0",
    impact: "High",
    cluster: "Dub / post",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "melody-to-modular-synth",
    title: "Melody to Modular Synth",
    models: "basic-pitch",
    licenses: "basic-pitch: Apache-2.0",
    impact: "Med",
    cluster: "Modular + MIDI",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "compare-stemmers",
    title: "Compare Stemmers",
    models: "demucs-v4, demucs-v4-ht",
    licenses: "demucs-v4: MIT; demucs-v4-ht: MIT",
    impact: "Med",
    cluster: "Stems compare",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "stem-lyrics-to-ace",
    title: "Stem Lyrics to ACE",
    models: "demucs-v4, whisper-large-v3-turbo, ace-step-1.5-2b-turbo",
    licenses:
      "demucs-v4: MIT; whisper-large-v3-turbo: MIT; ace-step-1.5-2b-turbo: MIT",
    impact: "High",
    cluster: "ASR + T2M",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe (re-check ACE seed SPDX)",
    tone: "safe",
  },
  {
    id: "localize-dialogue-a-to-b",
    title: "Localize Dialogue (A→B)",
    models: "deepfilternet-v3, seamless-m4t-v2-large",
    licenses: "deepfilternet-v3: MIT; seamless-m4t-v2-large: CC-BY-NC-4.0",
    impact: "High",
    cluster: "Localization / S2ST",
    commercial: "Not safe",
    conference: "OK with attribution (NC weights)",
    final: "Not commercial · Conference with attribution",
    tone: "nc",
  },
  {
    id: "denoise-diarize-transcribe",
    title: "Denoise, Diarize and Transcribe",
    models: "deepfilternet-v3, whisper-large-v3-turbo, pyannote-diarization-3.1",
    licenses:
      "deepfilternet-v3: MIT; whisper-large-v3-turbo: MIT; pyannote-diarization-3.1: MIT",
    impact: "Med",
    cluster: "ASR + speakers",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe (cite pyannote; HF gated)",
    tone: "safe",
  },
  {
    id: "isolate-vocals-to-voice-convert",
    title: "Isolate to convert",
    models: "demucs-v4, deepfilternet-v3, rvc-v2-base",
    licenses: "demucs-v4: MIT; deepfilternet-v3: MIT; rvc-v2-base: MIT",
    impact: "Med",
    cluster: "Stems + RVC",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "extract-lyrics-to-music-with-ace-step",
    title: "Isolate to generate",
    models: "whisper-large-v3-turbo, ace-step-1.5",
    licenses: "whisper-large-v3-turbo: MIT; ace-step-1.5: MIT",
    impact: "Med",
    cluster: "ASR + T2M",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "isolate-vocals-to-transcribe",
    title: "Isolate to transcribe",
    models: "demucs-v4, whisper-large-v3-turbo",
    licenses: "demucs-v4: MIT; whisper-large-v3-turbo: MIT",
    impact: "Med",
    cluster: "Stems + ASR",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "modular-generative-rack",
    title: "Modular Generative Rack",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Med",
    cluster: "Modular teach",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "prompt-modular-synth",
    title: "Prompt Modular Synth",
    models: "kokoro-82m",
    licenses: "kokoro-82m: Apache-2.0",
    impact: "Med",
    cluster: "Modular teach",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "ambisonic-vr-preview",
    title: "Ambisonic VR Preview",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Immersive",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "karaoke-stems",
    title: "Karaoke Stems",
    models: "demucs-v4",
    licenses: "demucs-v4: MIT",
    impact: "Low",
    cluster: "Stems",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "midi-automation-demo",
    title: "MIDI Automation Demo",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Control I/O",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "object-spatial-demo",
    title: "Object Spatial Demo",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Immersive",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "simple-fm-synth",
    title: "Simple FM Synth",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Modular teach",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "sing-from-midi",
    title: "Sing from MIDI",
    models: "diffsinger-opencpop",
    licenses: "diffsinger-opencpop: MIT",
    impact: "Low",
    cluster: "Singing synth",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "stems-to-spatial",
    title: "Stems to Spatial",
    models: "demucs-v4-objects, object-placement-heuristic",
    licenses: "demucs-v4-objects: MIT; object-placement-heuristic: MIT",
    impact: "Low",
    cluster: "Immersive",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "surround-downmix",
    title: "Surround downmix",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Immersive",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "surround-mix",
    title: "Surround Mix",
    models: "—",
    licenses: "— (DSP / no AI weights)",
    impact: "Low",
    cluster: "Immersive",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "transcribe-to-midi",
    title: "Transcribe to MIDI",
    models: "basic-pitch",
    licenses: "basic-pitch: Apache-2.0",
    impact: "Low",
    cluster: "Melody→regen",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "transcribe-to-synth",
    title: "Transcribe to Synth",
    models: "basic-pitch",
    licenses: "basic-pitch: Apache-2.0",
    impact: "Low",
    cluster: "Live MIDI bridge",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "voice-convert-demo",
    title: "Voice Convert Demo",
    models: "rvc-v2-base",
    licenses: "rvc-v2-base: MIT",
    impact: "Low",
    cluster: "TTS / voice",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "song-cover-remix",
    title: "Song Cover / Remix",
    models: "demucs-v4, basic-pitch, musicgen-melody-small, rvc-v2-base",
    licenses:
      "demucs-v4: MIT; basic-pitch: Apache-2.0; musicgen-melody-small: CC-BY-NC-4.0; rvc-v2-base: MIT",
    impact: "High",
    cluster: "Compound multi-AI",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "text-to-music",
    title: "Text to Music- MusicGen",
    models: "musicgen-small",
    licenses: "musicgen-small: CC-BY-NC-4.0",
    impact: "High",
    cluster: "Text→music",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "transcribe-and-regenerate",
    title: "Transcribe and Regenerate",
    models: "basic-pitch, musicgen-melody-small",
    licenses: "basic-pitch: Apache-2.0; musicgen-melody-small: CC-BY-NC-4.0",
    impact: "High",
    cluster: "Melody→regen",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "voice-cloning",
    title: "Voice Cloning",
    models: "f5-tts-base",
    licenses: "f5-tts-base: CC-BY-NC-4.0",
    impact: "High",
    cluster: "TTS / voice",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "stable-audio",
    title: "Text to Music- Stable Audio",
    models: "stable-audio-open-1.0",
    licenses: "stable-audio-open-1.0: LicenseRef-StabilityAI-Community",
    impact: "Med",
    cluster: "Text→music",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "ai-midi-to-hardware",
    title: "AI MIDI to Hardware",
    models: "musicgen-melody-small",
    licenses: "musicgen-melody-small: CC-BY-NC-4.0",
    impact: "Low",
    cluster: "Live MIDI bridge",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "hum-to-full-track",
    title: "Hum / Melody -> Full Track",
    models: "basic-pitch, musicgen-melody-small",
    licenses: "basic-pitch: Apache-2.0; musicgen-melody-small: CC-BY-NC-4.0",
    impact: "Low",
    cluster: "Melody→regen",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "keyboard-to-music",
    title: "Keyboard to Music",
    models: "musicgen-melody-small",
    licenses: "musicgen-melody-small: CC-BY-NC-4.0",
    impact: "Low",
    cluster: "Live MIDI bridge",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "rave-timbre-transfer",
    title: "RAVE Timbre Transfer",
    models: "rave-v1",
    licenses: "rave-v1: CC-BY-NC-4.0",
    impact: "Low",
    cluster: "Neural synth",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "neural-modular-rack",
    title: "Neural Modular Rack",
    models: "ace-step-1.5",
    licenses: "ace-step-1.5: MIT (Granulate / Filter / Mix are DSP, no weights)",
    impact: "Med",
    cluster: "Modular + AI",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
  {
    id: "self-playing-neural-rack",
    title: "Self-Playing Neural Rack",
    models: "ace-step-1.5, rave-v1, rawnet2-asvspoof",
    licenses:
      "ace-step-1.5: MIT; rave-v1: CC-BY-NC-4.0; rawnet2-asvspoof: TBD",
    impact: "Med",
    cluster: "Modular + AI",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / authenticity TBD)",
    tone: "nc",
  },
  {
    id: "stem-to-remix",
    title: "Stem to Remix",
    models: "demucs-v4, basic-pitch, musicgen-melody-small",
    licenses:
      "demucs-v4: MIT; basic-pitch: Apache-2.0; musicgen-melody-small: CC-BY-NC-4.0",
    impact: "Low",
    cluster: "Compound multi-AI",
    commercial: "Not safe",
    conference: "OK + cite NC",
    final: "Commercial Not safe · Conference OK (cite NC / Community)",
    tone: "nc",
  },
  {
    id: "authenticity-check",
    title: "Authenticity Check",
    models: "rawnet2-asvspoof",
    licenses: "rawnet2-asvspoof: TBD",
    impact: "Med",
    cluster: "Compliance",
    commercial: "Not safe",
    conference: "Caution",
    final: "Commercial Not safe · Conference Caution (license TBD)",
    tone: "caution",
  },
  {
    id: "watermark-embed-detect",
    title: "Watermark Embed and Detect",
    models: "audioseal-16bit",
    licenses: "audioseal-16bit: MIT",
    impact: "Med",
    cluster: "Compliance",
    commercial: "Safe",
    conference: "Safe",
    final: "Commercial Safe · Conference Safe",
    tone: "safe",
  },
];

export function templateLicenseSummary(): {
  total: number;
  commercialSafe: number;
  conferenceOnly: number;
  caution: number;
} {
  return {
    total: TEMPLATE_LICENSE_MATRIX.length,
    commercialSafe: TEMPLATE_LICENSE_MATRIX.filter((r) => r.tone === "safe").length,
    conferenceOnly: TEMPLATE_LICENSE_MATRIX.filter((r) => r.tone === "nc").length,
    caution: TEMPLATE_LICENSE_MATRIX.filter((r) => r.tone === "caution").length,
  };
}

export function isCommerciallyCleared(templateId: string): boolean {
  return TEMPLATE_LICENSE_MATRIX.some((r) => r.id === templateId && r.commercial === "Safe");
}
